/*=============================================================================
  CATHAY BANK INTELLIGENCE AGENT
  File: 09_ml_model_functions.sql
  Description: FIBO ontology resolution UDFs and ML prediction functions
  Execution Order: 9 of 10
=============================================================================*/

USE DATABASE CATHAY_BANK_DB;
USE SCHEMA ANALYTICS;
USE WAREHOUSE CATHAY_BANK_WH;

CREATE OR REPLACE FUNCTION CATHAY_BANK_DB.ANALYTICS.FIBO_RESOLVE_CONCEPT(CONCEPT_TERM VARCHAR)
RETURNS OBJECT
AS
$$
SELECT OBJECT_CONSTRUCT(
    'concept', fc.CLASS_NAME,
    'domain', fc.DOMAIN,
    'subdomain', fc.SUBDOMAIN,
    'definition', fc.DEFINITION,
    'regulatory_context', fc.REGULATORY_CONTEXT,
    'data_elements', fc.DATA_ELEMENTS,
    'iso_standard', fc.ISO_STANDARD,
    'synonyms', fc.SYNONYMS,
    'table_name', cm.TABLE_NAME,
    'column_mappings', cm.COLUMN_MAPPINGS,
    'query_context', cm.QUERY_CONTEXT,
    'related_regulations', (
        SELECT ARRAY_AGG(OBJECT_CONSTRUCT(
            'regulation', rm.REGULATION_NAME,
            'body', rm.REGULATION_BODY,
            'requirement_type', rm.REQUIREMENT_TYPE,
            'description', rm.DESCRIPTION,
            'reporting_frequency', rm.REPORTING_FREQUENCY
        ))
        FROM CATHAY_BANK_DB.ONTOLOGY.FIBO_REGULATORY_MAPPINGS rm
        WHERE rm.CLASS_URI = fc.CLASS_URI
    ),
    'relationships', (
        SELECT ARRAY_AGG(OBJECT_CONSTRUCT(
            'relationship_type', fr.RELATIONSHIP_TYPE,
            'target', tc.CLASS_NAME,
            'description', fr.DESCRIPTION
        ))
        FROM CATHAY_BANK_DB.ONTOLOGY.FIBO_RELATIONSHIPS fr
        JOIN CATHAY_BANK_DB.ONTOLOGY.FIBO_CLASSES tc ON fr.TARGET_CLASS_URI = tc.CLASS_URI
        WHERE fr.SOURCE_CLASS_URI = fc.CLASS_URI
    )
)
FROM CATHAY_BANK_DB.ONTOLOGY.FIBO_CLASSES fc
LEFT JOIN CATHAY_BANK_DB.ONTOLOGY.FIBO_CONCEPT_MAPPINGS cm ON fc.CLASS_URI = cm.CLASS_URI
WHERE LOWER(fc.CLASS_NAME) = LOWER(CONCEPT_TERM)
   OR LOWER(fc.SYNONYMS) LIKE '%' || LOWER(CONCEPT_TERM) || '%'
   OR LOWER(cm.CONCEPT_TERM) = LOWER(CONCEPT_TERM)
LIMIT 1
$$;

CREATE OR REPLACE FUNCTION CATHAY_BANK_DB.ANALYTICS.FIBO_GET_REGULATORY_REQUIREMENTS(FRAMEWORK_NAME VARCHAR)
RETURNS ARRAY
AS
$$
SELECT ARRAY_AGG(OBJECT_CONSTRUCT(
    'regulation', rm.REGULATION_NAME,
    'regulatory_body', rm.REGULATION_BODY,
    'requirement_type', rm.REQUIREMENT_TYPE,
    'description', rm.DESCRIPTION,
    'compliance_metrics', rm.COMPLIANCE_METRICS,
    'data_elements', rm.DATA_ELEMENTS,
    'reporting_frequency', rm.REPORTING_FREQUENCY,
    'penalty_context', rm.PENALTY_CONTEXT,
    'related_concept', fc.CLASS_NAME,
    'concept_definition', fc.DEFINITION
))
FROM CATHAY_BANK_DB.ONTOLOGY.FIBO_REGULATORY_MAPPINGS rm
JOIN CATHAY_BANK_DB.ONTOLOGY.FIBO_CLASSES fc ON rm.CLASS_URI = fc.CLASS_URI
WHERE LOWER(rm.REGULATION_NAME) LIKE '%' || LOWER(FRAMEWORK_NAME) || '%'
   OR LOWER(rm.REGULATION_BODY) LIKE '%' || LOWER(FRAMEWORK_NAME) || '%'
   OR LOWER(fc.DOMAIN) LIKE '%' || LOWER(FRAMEWORK_NAME) || '%'
$$;

CREATE OR REPLACE FUNCTION CATHAY_BANK_DB.ANALYTICS.FIBO_NAVIGATE_RELATIONSHIPS(CLASS_NAME_INPUT VARCHAR)
RETURNS ARRAY
AS
$$
SELECT ARRAY_AGG(OBJECT_CONSTRUCT(
    'source_concept', sc.CLASS_NAME,
    'relationship_type', fr.RELATIONSHIP_TYPE,
    'relationship_name', fr.RELATIONSHIP_NAME,
    'target_concept', tc.CLASS_NAME,
    'target_domain', tc.DOMAIN,
    'description', fr.DESCRIPTION,
    'cardinality', fr.CARDINALITY
))
FROM CATHAY_BANK_DB.ONTOLOGY.FIBO_RELATIONSHIPS fr
JOIN CATHAY_BANK_DB.ONTOLOGY.FIBO_CLASSES sc ON fr.SOURCE_CLASS_URI = sc.CLASS_URI
JOIN CATHAY_BANK_DB.ONTOLOGY.FIBO_CLASSES tc ON fr.TARGET_CLASS_URI = tc.CLASS_URI
WHERE LOWER(sc.CLASS_NAME) = LOWER(CLASS_NAME_INPUT)
   OR LOWER(tc.CLASS_NAME) = LOWER(CLASS_NAME_INPUT)
$$;

CREATE OR REPLACE FUNCTION CATHAY_BANK_DB.ANALYTICS.GET_CUSTOMER_RISK_PROFILE(CUST_ID NUMBER)
RETURNS OBJECT
AS
$$
SELECT OBJECT_CONSTRUCT(
    'customer_id', c.CUSTOMER_ID,
    'name', c.FIRST_NAME || ' ' || c.LAST_NAME,
    'segment', c.CUSTOMER_SEGMENT,
    'credit_score', c.CREDIT_SCORE,
    'risk_rating', c.RISK_RATING,
    'kyc_status', c.KYC_STATUS,
    'kyc_last_reviewed', c.KYC_LAST_REVIEWED::VARCHAR,
    'annual_income', c.ANNUAL_INCOME,
    'total_deposit_balance', COALESCE(a.TOTAL_BALANCE, 0),
    'total_accounts', COALESCE(a.ACCT_COUNT, 0),
    'total_loan_balance', COALESCE(l.LOAN_BALANCE, 0),
    'active_loans', COALESCE(l.LOAN_COUNT, 0),
    'delinquent_loans', COALESCE(l.DELINQUENT_COUNT, 0),
    'compliance_events', COALESCE(ce.EVENT_COUNT, 0),
    'open_compliance_events', COALESCE(ce.OPEN_EVENTS, 0),
    'sars_filed', COALESCE(ce.SAR_COUNT, 0),
    'recent_risk_score', ra.RISK_SCORE,
    'recent_risk_rating', ra.RISK_RATING,
    'support_cases', COALESCE(sc.CASE_COUNT, 0),
    'avg_satisfaction', COALESCE(sc.AVG_SAT, 0)
)
FROM CATHAY_BANK_DB.RAW.CUSTOMERS c
LEFT JOIN (
    SELECT CUSTOMER_ID, SUM(CURRENT_BALANCE) AS TOTAL_BALANCE, COUNT(*) AS ACCT_COUNT
    FROM CATHAY_BANK_DB.RAW.ACCOUNTS WHERE STATUS = 'ACTIVE' GROUP BY CUSTOMER_ID
) a ON c.CUSTOMER_ID = a.CUSTOMER_ID
LEFT JOIN (
    SELECT CUSTOMER_ID, SUM(CURRENT_BALANCE) AS LOAN_BALANCE, COUNT(*) AS LOAN_COUNT,
           SUM(CASE WHEN DELINQUENCY_STATUS != 'Current' THEN 1 ELSE 0 END) AS DELINQUENT_COUNT
    FROM CATHAY_BANK_DB.RAW.LOANS WHERE STATUS = 'ACTIVE' GROUP BY CUSTOMER_ID
) l ON c.CUSTOMER_ID = l.CUSTOMER_ID
LEFT JOIN (
    SELECT CUSTOMER_ID, COUNT(*) AS EVENT_COUNT,
           SUM(CASE WHEN STATUS NOT IN ('Resolved') THEN 1 ELSE 0 END) AS OPEN_EVENTS,
           SUM(CASE WHEN SAR_FILED THEN 1 ELSE 0 END) AS SAR_COUNT
    FROM CATHAY_BANK_DB.RAW.COMPLIANCE_EVENTS GROUP BY CUSTOMER_ID
) ce ON c.CUSTOMER_ID = ce.CUSTOMER_ID
LEFT JOIN (
    SELECT CUSTOMER_ID, RISK_SCORE, RISK_RATING
    FROM CATHAY_BANK_DB.RAW.RISK_ASSESSMENTS
    QUALIFY ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ORDER BY ASSESSMENT_DATE DESC) = 1
) ra ON c.CUSTOMER_ID = ra.CUSTOMER_ID
LEFT JOIN (
    SELECT CUSTOMER_ID, COUNT(*) AS CASE_COUNT, AVG(SATISFACTION_SCORE) AS AVG_SAT
    FROM CATHAY_BANK_DB.RAW.SUPPORT_CASES GROUP BY CUSTOMER_ID
) sc ON c.CUSTOMER_ID = sc.CUSTOMER_ID
WHERE c.CUSTOMER_ID = CUST_ID
$$;

CREATE OR REPLACE FUNCTION CATHAY_BANK_DB.ANALYTICS.GET_PORTFOLIO_SUMMARY()
RETURNS OBJECT
AS
$$
SELECT OBJECT_CONSTRUCT(
    'total_customers', (SELECT COUNT(*) FROM CATHAY_BANK_DB.RAW.CUSTOMERS WHERE IS_ACTIVE),
    'total_accounts', (SELECT COUNT(*) FROM CATHAY_BANK_DB.RAW.ACCOUNTS WHERE STATUS = 'ACTIVE'),
    'total_deposits', (SELECT ROUND(SUM(CURRENT_BALANCE), 2) FROM CATHAY_BANK_DB.RAW.ACCOUNTS WHERE STATUS = 'ACTIVE'),
    'avg_account_balance', (SELECT ROUND(AVG(CURRENT_BALANCE), 2) FROM CATHAY_BANK_DB.RAW.ACCOUNTS WHERE STATUS = 'ACTIVE'),
    'total_loans', (SELECT COUNT(*) FROM CATHAY_BANK_DB.RAW.LOANS WHERE STATUS = 'ACTIVE'),
    'total_loan_portfolio', (SELECT ROUND(SUM(CURRENT_BALANCE), 2) FROM CATHAY_BANK_DB.RAW.LOANS WHERE STATUS = 'ACTIVE'),
    'delinquency_rate', (SELECT ROUND(AVG(CASE WHEN DELINQUENCY_STATUS != 'Current' THEN 1.0 ELSE 0.0 END) * 100, 2) FROM CATHAY_BANK_DB.RAW.LOANS WHERE STATUS = 'ACTIVE'),
    'default_count', (SELECT COUNT(*) FROM CATHAY_BANK_DB.RAW.LOANS WHERE STATUS = 'DEFAULT'),
    'avg_credit_score', (SELECT ROUND(AVG(CREDIT_SCORE), 0) FROM CATHAY_BANK_DB.RAW.CUSTOMERS WHERE IS_ACTIVE),
    'open_compliance_events', (SELECT COUNT(*) FROM CATHAY_BANK_DB.RAW.COMPLIANCE_EVENTS WHERE STATUS NOT IN ('Resolved')),
    'sars_filed_ytd', (SELECT COUNT(*) FROM CATHAY_BANK_DB.RAW.COMPLIANCE_EVENTS WHERE SAR_FILED AND SAR_FILING_DATE >= DATE_TRUNC('year', CURRENT_DATE())),
    'open_support_cases', (SELECT COUNT(*) FROM CATHAY_BANK_DB.RAW.SUPPORT_CASES WHERE STATUS IN ('Open', 'In Progress', 'Pending Customer')),
    'avg_csat', (SELECT ROUND(AVG(SATISFACTION_SCORE), 1) FROM CATHAY_BANK_DB.RAW.SUPPORT_CASES WHERE SATISFACTION_SCORE IS NOT NULL),
    'branch_count', (SELECT COUNT(*) FROM CATHAY_BANK_DB.RAW.BRANCHES WHERE IS_ACTIVE)
)
$$;

CREATE OR REPLACE FUNCTION CATHAY_BANK_DB.ANALYTICS.GET_COMPLIANCE_SUMMARY()
RETURNS OBJECT
AS
$$
SELECT OBJECT_CONSTRUCT(
    'total_events', (SELECT COUNT(*) FROM CATHAY_BANK_DB.RAW.COMPLIANCE_EVENTS),
    'open_events', (SELECT COUNT(*) FROM CATHAY_BANK_DB.RAW.COMPLIANCE_EVENTS WHERE STATUS IN ('Open', 'Escalated', 'Under Investigation')),
    'critical_events', (SELECT COUNT(*) FROM CATHAY_BANK_DB.RAW.COMPLIANCE_EVENTS WHERE SEVERITY = 'Critical' AND STATUS NOT IN ('Resolved')),
    'high_severity_events', (SELECT COUNT(*) FROM CATHAY_BANK_DB.RAW.COMPLIANCE_EVENTS WHERE SEVERITY = 'High' AND STATUS NOT IN ('Resolved')),
    'sars_filed', (SELECT COUNT(*) FROM CATHAY_BANK_DB.RAW.COMPLIANCE_EVENTS WHERE SAR_FILED),
    'ctrs_filed', (SELECT COUNT(*) FROM CATHAY_BANK_DB.RAW.COMPLIANCE_EVENTS WHERE CTR_FILED),
    'events_by_category', (
        SELECT ARRAY_AGG(OBJECT_CONSTRUCT('category', EVENT_CATEGORY, 'count', CNT))
        FROM (SELECT EVENT_CATEGORY, COUNT(*) AS CNT FROM CATHAY_BANK_DB.RAW.COMPLIANCE_EVENTS GROUP BY EVENT_CATEGORY)
    ),
    'events_by_severity', (
        SELECT ARRAY_AGG(OBJECT_CONSTRUCT('severity', SEVERITY, 'count', CNT))
        FROM (SELECT SEVERITY, COUNT(*) AS CNT FROM CATHAY_BANK_DB.RAW.COMPLIANCE_EVENTS GROUP BY SEVERITY)
    ),
    'avg_resolution_days', (
        SELECT ROUND(AVG(DATEDIFF('day', DETECTED_DATE, RESOLVED_DATE)), 1)
        FROM CATHAY_BANK_DB.RAW.COMPLIANCE_EVENTS WHERE RESOLVED_DATE IS NOT NULL
    ),
    'kyc_expired_count', (SELECT COUNT(*) FROM CATHAY_BANK_DB.RAW.CUSTOMERS WHERE KYC_STATUS = 'Expired' AND IS_ACTIVE),
    'kyc_pending_count', (SELECT COUNT(*) FROM CATHAY_BANK_DB.RAW.CUSTOMERS WHERE KYC_STATUS = 'Pending' AND IS_ACTIVE),
    'high_risk_customers', (SELECT COUNT(*) FROM CATHAY_BANK_DB.RAW.CUSTOMERS WHERE RISK_RATING = 'High' AND IS_ACTIVE)
)
$$;
