/*=============================================================================
  CATHAY BANK INTELLIGENCE AGENT
  File: 05_create_views.sql
  Description: Analytical views for business intelligence and agent consumption
  Execution Order: 5 of 10
=============================================================================*/

USE DATABASE CATHAY_BANK_DB;
USE SCHEMA ANALYTICS;
USE WAREHOUSE CATHAY_BANK_WH;

CREATE OR REPLACE VIEW CUSTOMER_360 AS
SELECT
    c.CUSTOMER_ID,
    c.FIRST_NAME,
    c.LAST_NAME,
    c.FIRST_NAME || ' ' || c.LAST_NAME AS FULL_NAME,
    c.EMAIL,
    c.PHONE,
    c.DATE_OF_BIRTH,
    DATEDIFF('year', c.DATE_OF_BIRTH, CURRENT_DATE()) AS AGE,
    c.CITY,
    c.STATE,
    c.ZIP_CODE,
    c.CUSTOMER_SEGMENT,
    c.CUSTOMER_SINCE,
    DATEDIFF('year', c.CUSTOMER_SINCE, CURRENT_DATE()) AS TENURE_YEARS,
    c.PREFERRED_LANGUAGE,
    c.RISK_RATING,
    c.KYC_STATUS,
    c.KYC_LAST_REVIEWED,
    c.ANNUAL_INCOME,
    c.EMPLOYMENT_STATUS,
    c.EMPLOYER_NAME,
    c.CREDIT_SCORE,
    c.IS_ACTIVE,
    COALESCE(acct.TOTAL_ACCOUNTS, 0) AS TOTAL_ACCOUNTS,
    COALESCE(acct.ACTIVE_ACCOUNTS, 0) AS ACTIVE_ACCOUNTS,
    COALESCE(acct.TOTAL_DEPOSIT_BALANCE, 0) AS TOTAL_DEPOSIT_BALANCE,
    COALESCE(loan_agg.TOTAL_LOANS, 0) AS TOTAL_LOANS,
    COALESCE(loan_agg.ACTIVE_LOANS, 0) AS ACTIVE_LOANS,
    COALESCE(loan_agg.TOTAL_LOAN_BALANCE, 0) AS TOTAL_LOAN_BALANCE,
    COALESCE(loan_agg.TOTAL_ORIGINAL_LOAN_AMOUNT, 0) AS TOTAL_ORIGINAL_LOAN_AMOUNT,
    COALESCE(txn_agg.TRANSACTION_COUNT_90D, 0) AS TRANSACTION_COUNT_90D,
    COALESCE(txn_agg.TOTAL_CREDITS_90D, 0) AS TOTAL_CREDITS_90D,
    COALESCE(txn_agg.TOTAL_DEBITS_90D, 0) AS TOTAL_DEBITS_90D,
    COALESCE(comp_agg.COMPLIANCE_EVENTS, 0) AS COMPLIANCE_EVENT_COUNT,
    COALESCE(comp_agg.OPEN_COMPLIANCE_EVENTS, 0) AS OPEN_COMPLIANCE_EVENTS,
    COALESCE(sup_agg.SUPPORT_CASES, 0) AS SUPPORT_CASE_COUNT,
    COALESCE(sup_agg.OPEN_CASES, 0) AS OPEN_SUPPORT_CASES,
    COALESCE(sup_agg.AVG_SATISFACTION, 0) AS AVG_SATISFACTION_SCORE,
    COALESCE(acct.TOTAL_DEPOSIT_BALANCE, 0) + COALESCE(loan_agg.TOTAL_ORIGINAL_LOAN_AMOUNT, 0) AS TOTAL_RELATIONSHIP_VALUE
FROM CATHAY_BANK_DB.RAW.CUSTOMERS c
LEFT JOIN (
    SELECT
        CUSTOMER_ID,
        COUNT(*) AS TOTAL_ACCOUNTS,
        SUM(CASE WHEN STATUS = 'ACTIVE' THEN 1 ELSE 0 END) AS ACTIVE_ACCOUNTS,
        SUM(CASE WHEN STATUS = 'ACTIVE' THEN CURRENT_BALANCE ELSE 0 END) AS TOTAL_DEPOSIT_BALANCE
    FROM CATHAY_BANK_DB.RAW.ACCOUNTS
    GROUP BY CUSTOMER_ID
) acct ON c.CUSTOMER_ID = acct.CUSTOMER_ID
LEFT JOIN (
    SELECT
        CUSTOMER_ID,
        COUNT(*) AS TOTAL_LOANS,
        SUM(CASE WHEN STATUS = 'ACTIVE' THEN 1 ELSE 0 END) AS ACTIVE_LOANS,
        SUM(CASE WHEN STATUS = 'ACTIVE' THEN CURRENT_BALANCE ELSE 0 END) AS TOTAL_LOAN_BALANCE,
        SUM(ORIGINAL_AMOUNT) AS TOTAL_ORIGINAL_LOAN_AMOUNT
    FROM CATHAY_BANK_DB.RAW.LOANS
    GROUP BY CUSTOMER_ID
) loan_agg ON c.CUSTOMER_ID = loan_agg.CUSTOMER_ID
LEFT JOIN (
    SELECT
        a.CUSTOMER_ID,
        COUNT(*) AS TRANSACTION_COUNT_90D,
        SUM(CASE WHEN t.AMOUNT > 0 THEN t.AMOUNT ELSE 0 END) AS TOTAL_CREDITS_90D,
        SUM(CASE WHEN t.AMOUNT < 0 THEN ABS(t.AMOUNT) ELSE 0 END) AS TOTAL_DEBITS_90D
    FROM CATHAY_BANK_DB.RAW.TRANSACTIONS t
    JOIN CATHAY_BANK_DB.RAW.ACCOUNTS a ON t.ACCOUNT_ID = a.ACCOUNT_ID
    WHERE t.TRANSACTION_DATE >= DATEADD('day', -90, CURRENT_TIMESTAMP())
    GROUP BY a.CUSTOMER_ID
) txn_agg ON c.CUSTOMER_ID = txn_agg.CUSTOMER_ID
LEFT JOIN (
    SELECT
        CUSTOMER_ID,
        COUNT(*) AS COMPLIANCE_EVENTS,
        SUM(CASE WHEN STATUS NOT IN ('Resolved') THEN 1 ELSE 0 END) AS OPEN_COMPLIANCE_EVENTS
    FROM CATHAY_BANK_DB.RAW.COMPLIANCE_EVENTS
    GROUP BY CUSTOMER_ID
) comp_agg ON c.CUSTOMER_ID = comp_agg.CUSTOMER_ID
LEFT JOIN (
    SELECT
        CUSTOMER_ID,
        COUNT(*) AS SUPPORT_CASES,
        SUM(CASE WHEN STATUS IN ('Open', 'In Progress', 'Pending Customer') THEN 1 ELSE 0 END) AS OPEN_CASES,
        ROUND(AVG(SATISFACTION_SCORE), 1) AS AVG_SATISFACTION
    FROM CATHAY_BANK_DB.RAW.SUPPORT_CASES
    GROUP BY CUSTOMER_ID
) sup_agg ON c.CUSTOMER_ID = sup_agg.CUSTOMER_ID;

CREATE OR REPLACE VIEW LOAN_PORTFOLIO_ANALYSIS AS
SELECT
    l.LOAN_ID,
    l.CUSTOMER_ID,
    c.FIRST_NAME || ' ' || c.LAST_NAME AS BORROWER_NAME,
    c.CUSTOMER_SEGMENT,
    c.CREDIT_SCORE,
    l.LOAN_TYPE,
    l.LOAN_PURPOSE,
    l.ORIGINAL_AMOUNT,
    l.CURRENT_BALANCE,
    l.INTEREST_RATE,
    l.RATE_TYPE,
    l.TERM_MONTHS,
    l.MONTHLY_PAYMENT,
    l.ORIGINATION_DATE,
    l.MATURITY_DATE,
    DATEDIFF('month', l.ORIGINATION_DATE, CURRENT_DATE()) AS MONTHS_SINCE_ORIGINATION,
    DATEDIFF('month', CURRENT_DATE(), l.MATURITY_DATE) AS MONTHS_TO_MATURITY,
    l.COLLATERAL_TYPE,
    l.COLLATERAL_VALUE,
    l.LTV_RATIO,
    l.DTI_RATIO,
    l.DELINQUENCY_STATUS,
    l.DAYS_PAST_DUE,
    l.RISK_GRADE,
    l.STATUS,
    CASE
        WHEN l.DELINQUENCY_STATUS = 'Current' THEN 'Performing'
        WHEN l.DELINQUENCY_STATUS = '30 Days Past Due' THEN 'Watch'
        WHEN l.DELINQUENCY_STATUS = '60 Days Past Due' THEN 'Substandard'
        ELSE 'Doubtful'
    END AS RISK_CLASSIFICATION,
    ROUND(l.ORIGINAL_AMOUNT - l.CURRENT_BALANCE, 2) AS PRINCIPAL_PAID,
    ROUND((l.ORIGINAL_AMOUNT - l.CURRENT_BALANCE) / NULLIF(l.ORIGINAL_AMOUNT, 0) * 100, 2) AS PAYDOWN_PERCENTAGE,
    a.BRANCH_NAME,
    a.BRANCH_STATE
FROM CATHAY_BANK_DB.RAW.LOANS l
JOIN CATHAY_BANK_DB.RAW.CUSTOMERS c ON l.CUSTOMER_ID = c.CUSTOMER_ID
LEFT JOIN CATHAY_BANK_DB.RAW.ACCOUNTS a ON l.ACCOUNT_ID = a.ACCOUNT_ID;

CREATE OR REPLACE VIEW COMPLIANCE_DASHBOARD AS
SELECT
    ce.EVENT_ID,
    ce.CUSTOMER_ID,
    c.FIRST_NAME || ' ' || c.LAST_NAME AS CUSTOMER_NAME,
    c.RISK_RATING AS CUSTOMER_RISK_RATING,
    c.KYC_STATUS,
    ce.ACCOUNT_ID,
    ce.EVENT_TYPE,
    ce.EVENT_CATEGORY,
    ce.REGULATORY_FRAMEWORK,
    ce.SEVERITY,
    ce.STATUS,
    ce.DESCRIPTION,
    ce.DETECTION_METHOD,
    ce.DETECTED_DATE,
    ce.RESOLVED_DATE,
    CASE WHEN ce.RESOLVED_DATE IS NOT NULL
        THEN DATEDIFF('day', ce.DETECTED_DATE, ce.RESOLVED_DATE)
        ELSE DATEDIFF('day', ce.DETECTED_DATE, CURRENT_TIMESTAMP())
    END AS DAYS_OPEN,
    ce.ASSIGNED_TO,
    ce.RESOLUTION_NOTES,
    ce.SAR_FILED,
    ce.SAR_FILING_DATE,
    ce.CTR_FILED,
    ce.REGULATORY_REPORT_ID,
    CASE
        WHEN ce.STATUS IN ('Open', 'Escalated') AND ce.SEVERITY IN ('Critical', 'High') THEN 'Immediate Action Required'
        WHEN ce.STATUS IN ('Open', 'Escalated') THEN 'Review Required'
        WHEN ce.STATUS = 'Under Investigation' THEN 'In Progress'
        ELSE 'Resolved/Closed'
    END AS ACTION_PRIORITY
FROM CATHAY_BANK_DB.RAW.COMPLIANCE_EVENTS ce
LEFT JOIN CATHAY_BANK_DB.RAW.CUSTOMERS c ON ce.CUSTOMER_ID = c.CUSTOMER_ID;

CREATE OR REPLACE VIEW TRANSACTION_ANALYTICS AS
SELECT
    t.TRANSACTION_ID,
    t.ACCOUNT_ID,
    a.CUSTOMER_ID,
    a.ACCOUNT_TYPE,
    a.BRANCH_NAME,
    a.BRANCH_STATE,
    t.TRANSACTION_DATE,
    t.POSTED_DATE,
    DATE_TRUNC('month', t.TRANSACTION_DATE) AS TRANSACTION_MONTH,
    DATE_TRUNC('week', t.TRANSACTION_DATE) AS TRANSACTION_WEEK,
    t.TRANSACTION_TYPE,
    t.TRANSACTION_CATEGORY,
    t.AMOUNT,
    ABS(t.AMOUNT) AS ABSOLUTE_AMOUNT,
    CASE WHEN t.AMOUNT > 0 THEN 'Credit' ELSE 'Debit' END AS FLOW_DIRECTION,
    t.CURRENCY,
    t.DESCRIPTION,
    t.MERCHANT_NAME,
    t.MERCHANT_CATEGORY,
    t.CHANNEL,
    t.IS_RECURRING,
    t.IS_FLAGGED,
    t.FLAG_REASON,
    t.BALANCE_AFTER
FROM CATHAY_BANK_DB.RAW.TRANSACTIONS t
JOIN CATHAY_BANK_DB.RAW.ACCOUNTS a ON t.ACCOUNT_ID = a.ACCOUNT_ID;

CREATE OR REPLACE VIEW BRANCH_PERFORMANCE AS
SELECT
    b.BRANCH_ID,
    b.BRANCH_NAME,
    b.BRANCH_CODE,
    b.CITY,
    b.STATE,
    b.REGION,
    b.MANAGER_NAME,
    b.OPENED_DATE AS BRANCH_OPENED_DATE,
    DATEDIFF('year', b.OPENED_DATE, CURRENT_DATE()) AS YEARS_IN_OPERATION,
    COALESCE(acct_stats.TOTAL_ACCOUNTS, 0) AS TOTAL_ACCOUNTS,
    COALESCE(acct_stats.ACTIVE_ACCOUNTS, 0) AS ACTIVE_ACCOUNTS,
    COALESCE(acct_stats.TOTAL_DEPOSITS, 0) AS TOTAL_DEPOSITS,
    COALESCE(acct_stats.AVG_BALANCE, 0) AS AVG_ACCOUNT_BALANCE,
    COALESCE(acct_stats.UNIQUE_CUSTOMERS, 0) AS UNIQUE_CUSTOMERS,
    COALESCE(sup_stats.TOTAL_CASES, 0) AS SUPPORT_CASES,
    COALESCE(sup_stats.AVG_CSAT, 0) AS AVG_CUSTOMER_SATISFACTION
FROM CATHAY_BANK_DB.RAW.BRANCHES b
LEFT JOIN (
    SELECT
        BRANCH_ID,
        COUNT(*) AS TOTAL_ACCOUNTS,
        SUM(CASE WHEN STATUS = 'ACTIVE' THEN 1 ELSE 0 END) AS ACTIVE_ACCOUNTS,
        SUM(CASE WHEN STATUS = 'ACTIVE' THEN CURRENT_BALANCE ELSE 0 END) AS TOTAL_DEPOSITS,
        ROUND(AVG(CASE WHEN STATUS = 'ACTIVE' THEN CURRENT_BALANCE END), 2) AS AVG_BALANCE,
        COUNT(DISTINCT CUSTOMER_ID) AS UNIQUE_CUSTOMERS
    FROM CATHAY_BANK_DB.RAW.ACCOUNTS
    GROUP BY BRANCH_ID
) acct_stats ON b.BRANCH_ID = acct_stats.BRANCH_ID
LEFT JOIN (
    SELECT
        a.BRANCH_ID,
        COUNT(*) AS TOTAL_CASES,
        ROUND(AVG(sc.SATISFACTION_SCORE), 1) AS AVG_CSAT
    FROM CATHAY_BANK_DB.RAW.SUPPORT_CASES sc
    JOIN CATHAY_BANK_DB.RAW.ACCOUNTS a ON sc.ACCOUNT_ID = a.ACCOUNT_ID
    GROUP BY a.BRANCH_ID
) sup_stats ON b.BRANCH_ID = sup_stats.BRANCH_ID;

CREATE OR REPLACE VIEW RISK_OVERVIEW AS
SELECT
    ra.ASSESSMENT_ID,
    ra.CUSTOMER_ID,
    c.FIRST_NAME || ' ' || c.LAST_NAME AS CUSTOMER_NAME,
    c.CUSTOMER_SEGMENT,
    c.CREDIT_SCORE,
    ra.ACCOUNT_ID,
    ra.LOAN_ID,
    ra.ASSESSMENT_TYPE,
    ra.RISK_CATEGORY,
    ra.RISK_SCORE,
    ra.RISK_RATING,
    ra.RISK_FACTORS,
    ra.ASSESSMENT_DATE,
    ra.NEXT_REVIEW_DATE,
    CASE WHEN ra.NEXT_REVIEW_DATE < CURRENT_DATE() THEN TRUE ELSE FALSE END AS REVIEW_OVERDUE,
    DATEDIFF('day', ra.ASSESSMENT_DATE, CURRENT_DATE()) AS DAYS_SINCE_ASSESSMENT,
    ra.ASSESSOR,
    ra.MODEL_VERSION,
    ra.STATUS,
    ra.NOTES,
    l.LOAN_TYPE,
    l.DELINQUENCY_STATUS,
    l.DAYS_PAST_DUE
FROM CATHAY_BANK_DB.RAW.RISK_ASSESSMENTS ra
LEFT JOIN CATHAY_BANK_DB.RAW.CUSTOMERS c ON ra.CUSTOMER_ID = c.CUSTOMER_ID
LEFT JOIN CATHAY_BANK_DB.RAW.LOANS l ON ra.LOAN_ID = l.LOAN_ID;

CREATE OR REPLACE VIEW SUPPORT_ANALYTICS AS
SELECT
    sc.CASE_ID,
    sc.CASE_NUMBER,
    sc.CUSTOMER_ID,
    c.FIRST_NAME || ' ' || c.LAST_NAME AS CUSTOMER_NAME,
    c.CUSTOMER_SEGMENT,
    sc.ACCOUNT_ID,
    sc.CATEGORY,
    sc.SUBCATEGORY,
    sc.PRIORITY,
    sc.STATUS,
    sc.CHANNEL,
    sc.SUBJECT,
    sc.DESCRIPTION AS CASE_DESCRIPTION,
    sc.RESOLUTION,
    sc.ASSIGNED_TO,
    sc.OPENED_DATE,
    sc.FIRST_RESPONSE_DATE,
    sc.RESOLVED_DATE,
    sc.CLOSED_DATE,
    CASE WHEN sc.FIRST_RESPONSE_DATE IS NOT NULL
        THEN DATEDIFF('hour', sc.OPENED_DATE, sc.FIRST_RESPONSE_DATE)
        ELSE NULL
    END AS FIRST_RESPONSE_HOURS,
    CASE WHEN sc.RESOLVED_DATE IS NOT NULL
        THEN DATEDIFF('hour', sc.OPENED_DATE, sc.RESOLVED_DATE)
        ELSE DATEDIFF('hour', sc.OPENED_DATE, CURRENT_TIMESTAMP())
    END AS RESOLUTION_HOURS,
    sc.SATISFACTION_SCORE,
    DATE_TRUNC('month', sc.OPENED_DATE) AS OPENED_MONTH,
    a.BRANCH_NAME,
    a.BRANCH_STATE
FROM CATHAY_BANK_DB.RAW.SUPPORT_CASES sc
LEFT JOIN CATHAY_BANK_DB.RAW.CUSTOMERS c ON sc.CUSTOMER_ID = c.CUSTOMER_ID
LEFT JOIN CATHAY_BANK_DB.RAW.ACCOUNTS a ON sc.ACCOUNT_ID = a.ACCOUNT_ID;
