/*=============================================================================
  CATHAY BANK INTELLIGENCE AGENT
  File: 01_database_and_schema.sql
  Description: Database, schema, and warehouse infrastructure setup
  Execution Order: 1 of 10
=============================================================================*/

USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS CATHAY_BANK_DB;
USE DATABASE CATHAY_BANK_DB;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;
CREATE SCHEMA IF NOT EXISTS ONTOLOGY;
CREATE SCHEMA IF NOT EXISTS SEARCH;
CREATE SCHEMA IF NOT EXISTS ML;

CREATE OR REPLACE WAREHOUSE CATHAY_BANK_WH WITH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse for Cathay Bank Intelligence Agent';

USE WAREHOUSE CATHAY_BANK_WH;

GRANT USAGE ON DATABASE CATHAY_BANK_DB TO ROLE ACCOUNTADMIN;
GRANT USAGE ON SCHEMA CATHAY_BANK_DB.RAW TO ROLE ACCOUNTADMIN;
GRANT USAGE ON SCHEMA CATHAY_BANK_DB.ANALYTICS TO ROLE ACCOUNTADMIN;
GRANT USAGE ON SCHEMA CATHAY_BANK_DB.ONTOLOGY TO ROLE ACCOUNTADMIN;
GRANT USAGE ON SCHEMA CATHAY_BANK_DB.SEARCH TO ROLE ACCOUNTADMIN;
GRANT USAGE ON SCHEMA CATHAY_BANK_DB.ML TO ROLE ACCOUNTADMIN;
GRANT CREATE SEMANTIC VIEW ON SCHEMA CATHAY_BANK_DB.ANALYTICS TO ROLE ACCOUNTADMIN;
GRANT CREATE AGENT ON SCHEMA CATHAY_BANK_DB.ANALYTICS TO ROLE ACCOUNTADMIN;

ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';
