/*=============================================================================
  CATHAY BANK INTELLIGENCE AGENT
  File: 02_create_tables.sql
  Description: Core banking domain tables
  Execution Order: 2 of 10
=============================================================================*/

USE DATABASE CATHAY_BANK_DB;
USE SCHEMA RAW;
USE WAREHOUSE CATHAY_BANK_WH;

CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID         NUMBER(38,0) AUTOINCREMENT PRIMARY KEY,
    FIRST_NAME          VARCHAR(100) NOT NULL,
    LAST_NAME           VARCHAR(100) NOT NULL,
    EMAIL               VARCHAR(255),
    PHONE               VARCHAR(20),
    DATE_OF_BIRTH       DATE,
    SSN_LAST_FOUR       VARCHAR(4),
    ADDRESS_LINE1       VARCHAR(255),
    ADDRESS_LINE2       VARCHAR(255),
    CITY                VARCHAR(100),
    STATE               VARCHAR(2),
    ZIP_CODE            VARCHAR(10),
    COUNTRY             VARCHAR(50) DEFAULT 'US',
    CUSTOMER_SEGMENT    VARCHAR(50),
    CUSTOMER_SINCE      DATE,
    PREFERRED_LANGUAGE  VARCHAR(20) DEFAULT 'English',
    RISK_RATING         VARCHAR(20),
    KYC_STATUS          VARCHAR(30),
    KYC_LAST_REVIEWED   DATE,
    ANNUAL_INCOME       NUMBER(15,2),
    EMPLOYMENT_STATUS   VARCHAR(50),
    EMPLOYER_NAME       VARCHAR(200),
    CREDIT_SCORE        NUMBER(3,0),
    IS_ACTIVE           BOOLEAN DEFAULT TRUE,
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE ACCOUNTS (
    ACCOUNT_ID          NUMBER(38,0) AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID         NUMBER(38,0) NOT NULL REFERENCES CUSTOMERS(CUSTOMER_ID),
    ACCOUNT_NUMBER      VARCHAR(20) NOT NULL,
    ACCOUNT_TYPE        VARCHAR(50) NOT NULL,
    ACCOUNT_SUBTYPE     VARCHAR(50),
    CURRENCY            VARCHAR(3) DEFAULT 'USD',
    CURRENT_BALANCE     NUMBER(18,2) DEFAULT 0,
    AVAILABLE_BALANCE   NUMBER(18,2) DEFAULT 0,
    INTEREST_RATE       NUMBER(8,5),
    OVERDRAFT_LIMIT     NUMBER(15,2) DEFAULT 0,
    STATUS              VARCHAR(20) DEFAULT 'ACTIVE',
    OPENED_DATE         DATE NOT NULL,
    CLOSED_DATE         DATE,
    BRANCH_ID           NUMBER(38,0),
    BRANCH_NAME         VARCHAR(100),
    BRANCH_STATE        VARCHAR(2),
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE TRANSACTIONS (
    TRANSACTION_ID      NUMBER(38,0) AUTOINCREMENT PRIMARY KEY,
    ACCOUNT_ID          NUMBER(38,0) NOT NULL REFERENCES ACCOUNTS(ACCOUNT_ID),
    TRANSACTION_DATE    TIMESTAMP_NTZ NOT NULL,
    POSTED_DATE         DATE,
    TRANSACTION_TYPE    VARCHAR(50) NOT NULL,
    TRANSACTION_CATEGORY VARCHAR(100),
    AMOUNT              NUMBER(18,2) NOT NULL,
    CURRENCY            VARCHAR(3) DEFAULT 'USD',
    DESCRIPTION         VARCHAR(500),
    MERCHANT_NAME       VARCHAR(200),
    MERCHANT_CATEGORY   VARCHAR(100),
    CHANNEL             VARCHAR(50),
    REFERENCE_NUMBER    VARCHAR(50),
    IS_RECURRING        BOOLEAN DEFAULT FALSE,
    IS_FLAGGED          BOOLEAN DEFAULT FALSE,
    FLAG_REASON         VARCHAR(200),
    BALANCE_AFTER       NUMBER(18,2),
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE LOANS (
    LOAN_ID             NUMBER(38,0) AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID         NUMBER(38,0) NOT NULL REFERENCES CUSTOMERS(CUSTOMER_ID),
    ACCOUNT_ID          NUMBER(38,0) REFERENCES ACCOUNTS(ACCOUNT_ID),
    LOAN_TYPE           VARCHAR(50) NOT NULL,
    LOAN_PURPOSE        VARCHAR(100),
    ORIGINAL_AMOUNT     NUMBER(18,2) NOT NULL,
    CURRENT_BALANCE     NUMBER(18,2),
    INTEREST_RATE       NUMBER(8,5) NOT NULL,
    RATE_TYPE           VARCHAR(20),
    TERM_MONTHS         NUMBER(5,0),
    MONTHLY_PAYMENT     NUMBER(15,2),
    ORIGINATION_DATE    DATE NOT NULL,
    MATURITY_DATE       DATE,
    COLLATERAL_TYPE     VARCHAR(100),
    COLLATERAL_VALUE    NUMBER(18,2),
    LTV_RATIO           NUMBER(8,4),
    DTI_RATIO           NUMBER(8,4),
    DELINQUENCY_STATUS  VARCHAR(30) DEFAULT 'CURRENT',
    DAYS_PAST_DUE       NUMBER(5,0) DEFAULT 0,
    RISK_GRADE          VARCHAR(10),
    STATUS              VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE LOAN_PAYMENTS (
    PAYMENT_ID          NUMBER(38,0) AUTOINCREMENT PRIMARY KEY,
    LOAN_ID             NUMBER(38,0) NOT NULL REFERENCES LOANS(LOAN_ID),
    PAYMENT_DATE        DATE NOT NULL,
    DUE_DATE            DATE NOT NULL,
    PAYMENT_AMOUNT      NUMBER(15,2) NOT NULL,
    PRINCIPAL_AMOUNT    NUMBER(15,2),
    INTEREST_AMOUNT     NUMBER(15,2),
    ESCROW_AMOUNT       NUMBER(15,2),
    LATE_FEE            NUMBER(10,2) DEFAULT 0,
    PAYMENT_METHOD      VARCHAR(50),
    STATUS              VARCHAR(20),
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE COMPLIANCE_EVENTS (
    EVENT_ID            NUMBER(38,0) AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID         NUMBER(38,0) REFERENCES CUSTOMERS(CUSTOMER_ID),
    ACCOUNT_ID          NUMBER(38,0) REFERENCES ACCOUNTS(ACCOUNT_ID),
    EVENT_TYPE          VARCHAR(100) NOT NULL,
    EVENT_CATEGORY      VARCHAR(100),
    REGULATORY_FRAMEWORK VARCHAR(100),
    SEVERITY            VARCHAR(20),
    STATUS              VARCHAR(30),
    DESCRIPTION         VARCHAR(2000),
    DETECTION_METHOD    VARCHAR(100),
    DETECTED_DATE       TIMESTAMP_NTZ NOT NULL,
    RESOLVED_DATE       TIMESTAMP_NTZ,
    ASSIGNED_TO         VARCHAR(100),
    RESOLUTION_NOTES    VARCHAR(2000),
    SAR_FILED           BOOLEAN DEFAULT FALSE,
    SAR_FILING_DATE     DATE,
    CTR_FILED           BOOLEAN DEFAULT FALSE,
    REGULATORY_REPORT_ID VARCHAR(50),
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RISK_ASSESSMENTS (
    ASSESSMENT_ID       NUMBER(38,0) AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID         NUMBER(38,0) REFERENCES CUSTOMERS(CUSTOMER_ID),
    ACCOUNT_ID          NUMBER(38,0) REFERENCES ACCOUNTS(ACCOUNT_ID),
    LOAN_ID             NUMBER(38,0) REFERENCES LOANS(LOAN_ID),
    ASSESSMENT_TYPE     VARCHAR(100) NOT NULL,
    RISK_CATEGORY       VARCHAR(100),
    RISK_SCORE          NUMBER(10,4),
    RISK_RATING         VARCHAR(20),
    RISK_FACTORS        VARCHAR(2000),
    ASSESSMENT_DATE     DATE NOT NULL,
    NEXT_REVIEW_DATE    DATE,
    ASSESSOR            VARCHAR(100),
    MODEL_VERSION       VARCHAR(50),
    STATUS              VARCHAR(30),
    NOTES               VARCHAR(2000),
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE SUPPORT_CASES (
    CASE_ID             NUMBER(38,0) AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID         NUMBER(38,0) REFERENCES CUSTOMERS(CUSTOMER_ID),
    ACCOUNT_ID          NUMBER(38,0) REFERENCES ACCOUNTS(ACCOUNT_ID),
    CASE_NUMBER         VARCHAR(20) NOT NULL,
    CATEGORY            VARCHAR(100),
    SUBCATEGORY         VARCHAR(100),
    PRIORITY            VARCHAR(20),
    STATUS              VARCHAR(30),
    CHANNEL             VARCHAR(50),
    SUBJECT             VARCHAR(500),
    DESCRIPTION         VARCHAR(4000),
    RESOLUTION          VARCHAR(4000),
    ASSIGNED_TO         VARCHAR(100),
    OPENED_DATE         TIMESTAMP_NTZ NOT NULL,
    FIRST_RESPONSE_DATE TIMESTAMP_NTZ,
    RESOLVED_DATE       TIMESTAMP_NTZ,
    CLOSED_DATE         TIMESTAMP_NTZ,
    SATISFACTION_SCORE  NUMBER(2,1),
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE BRANCHES (
    BRANCH_ID           NUMBER(38,0) AUTOINCREMENT PRIMARY KEY,
    BRANCH_NAME         VARCHAR(200) NOT NULL,
    BRANCH_CODE         VARCHAR(10),
    ADDRESS_LINE1       VARCHAR(255),
    CITY                VARCHAR(100),
    STATE               VARCHAR(2),
    ZIP_CODE            VARCHAR(10),
    COUNTRY             VARCHAR(50) DEFAULT 'US',
    PHONE               VARCHAR(20),
    MANAGER_NAME        VARCHAR(200),
    REGION              VARCHAR(50),
    OPENED_DATE         DATE,
    IS_ACTIVE           BOOLEAN DEFAULT TRUE,
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE PRODUCTS (
    PRODUCT_ID          NUMBER(38,0) AUTOINCREMENT PRIMARY KEY,
    PRODUCT_NAME        VARCHAR(200) NOT NULL,
    PRODUCT_CATEGORY    VARCHAR(100),
    PRODUCT_TYPE        VARCHAR(100),
    DESCRIPTION         VARCHAR(2000),
    INTEREST_RATE_MIN   NUMBER(8,5),
    INTEREST_RATE_MAX   NUMBER(8,5),
    MIN_BALANCE         NUMBER(15,2),
    MONTHLY_FEE         NUMBER(10,2),
    IS_ACTIVE           BOOLEAN DEFAULT TRUE,
    EFFECTIVE_DATE      DATE,
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE REGULATORY_DOCUMENTS (
    DOCUMENT_ID         NUMBER(38,0) AUTOINCREMENT PRIMARY KEY,
    TITLE               VARCHAR(500) NOT NULL,
    DOCUMENT_TYPE       VARCHAR(100),
    REGULATORY_BODY     VARCHAR(100),
    FRAMEWORK           VARCHAR(100),
    CONTENT             VARCHAR(16777216),
    SUMMARY             VARCHAR(4000),
    EFFECTIVE_DATE      DATE,
    EXPIRATION_DATE     DATE,
    VERSION             VARCHAR(20),
    STATUS              VARCHAR(30),
    TAGS                VARCHAR(1000),
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
